backend:
  name: git-gateway
  branch: main
  repo: csclub-debug/site-draft-library-sir--11

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  # 1) MAIN SITE DATA (content/data.json) - No changes needed here, structure is perfect.
  - name: "site_data"
    label: "Main Site Data"
    files:
      - file: "content/data.json"
        label: "Main content (data.json)"
        name: "data"
        editor:
          preview: false
        fields:
          - label: "Announcements"
            name: "announcements"
            widget: "list"
            summary: "{{fields.title}} ({{fields.date}})"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Date", name: "date", widget: "datetime", required: true}
              - {label: "Body / Note", name: "body", widget: "text", required: true}

          - label: "Staff Members"
            name: "staff"
            widget: "list"
            summary: "{{fields.name}} - {{fields.role}}"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Role", name: "role", widget: "string"}
              - {label: "Image", name: "image", widget: "image", required: false}
              - {label: "Email", name: "email", widget: "string", required: false}
              - {label: "Phone", name: "phone", widget: "string", required: false}

          - label: "Books (Highlights)"
            name: "books"
            widget: "list"
            collapsed: true
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Author", name: "author", widget: "string", required: false}
              - {label: "Category", name: "category", widget: "string", required: false}
              - {label: "Year", name: "year", widget: "string", required: false}

          - label: "E-Resources"
            name: "eresources"
            widget: "list"
            collapsed: true
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}
              - {label: "Description", name: "description", widget: "text", required: false}

          - label: "Research Sites & AI Tools"
            name: "research_sites"
            widget: "list"
            collapsed: true
            summary: "{{fields.name}}"
            fields:
              - {label: "Site Name", name: "name", widget: "string"}
              - {label: "Tagline / Description", name: "tagline", widget: "string"}
              - {label: "External URL", name: "link", widget: "string", hint: "Must start with http:// or https://"}

  # 2) QUESTION PAPERS (content/qpapers.json) - FIX APPLIED HERE
  - name: "question_papers"
    label: "Question Papers"
    # --- FIX: 'file' is removed from the collection root and moved into 'files' ---
    files:
      - file: "content/qpapers.json"
        label: "Question Paper Data"
        name: "qpaper_root" # Using a more generic name for the file object
        fields:
          # The entire content of qpapers.json is defined as a list field inside this file object
          - name: "qpaper_data"
            label: "Department Bundles"
            widget: "list"
            label_singular: "Department Bundle"
            summary: "{{fields.department}}"
            fields:
              # --- Department Object Fields ---
              - label: "Department Name"
                name: "department"
                widget: "select"
                options:
                  - "BCA"
                  - "B.Sc Zoology"
                  - "B.Sc Chemistry"
                  - "B.Sc Microbiology"
                  - "B.Sc Biotechnology"
                  - "B.Sc Botany"
                  - "B.Sc Mathematics"
                  - "B.Sc Physics"
                  - "B.Sc Computer Science"
                  - "M.Sc Industrial Chemistry"
              - {label: "Tagline", name: "tagline", widget: "string", required: false, hint: "A short description of the papers in this bundle."}
              
              # --- Papers List Field ---
              - name: "papers" 
                label: "Individual Question Papers"
                widget: "list"
                label_singular: "Paper"
                summary: "{{fields.title}}"
                fields:
                  - {label: "Paper Title (e.g., Data Structures - 2024)", name: "title", widget: "string"}
                  - {label: "Google Drive Link", name: "link", widget: "string", hint: "Paste the public link of the question paper PDF"}

  # 3) BOOK CATALOG (content/books.json) - Structure is correct.
  - name: "catalog"
    label: "Book Catalog (OPAC)"
    files:
      - file: "content/books.json"
        label: "Book Records"
        name: "books_list"
        fields:
          - name: "books"
            label: "Book Records"
            label_singular: "Book Record"
            widget: "list"
            collapsed: true
            summary: "{{fields.accession_no}} - {{fields.title}}"
            fields:
              - {label: "Accession Number", name: "accession_no", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Author", name: "author", widget: "string"}
              - {label: "Subject / Department", name: "subject", widget: "string", required: false}
              - {label: "ISBN", name: "isbn", widget: "string", required: false}
              - {label: "Publisher", name: "publisher", widget: "string", required: false}